version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: ENVVALUES=$(env | base64 | tr -d '\n') && echo $ENVVALUES
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
